#master: salt-master
#
#proxy:
#  proxytype: ssh_sample
#  host: sim-device
#  username: netadmin
#  password: netadmin

master: salt-master

proxy:
  proxytype: srlinux_ssh
  host: 172.20.20.2
  username: linuxadmin
  password: "12345678"
