services:

  salt-master:
    build:
      context: .
      dockerfile: docker/master/Dockerfile
    container_name: salt-master
    hostname: salt-master
    networks:
      - salt-net
    volumes:
      - ./master/config:/etc/salt/master.d
      - ./master/file_roots:/srv/salt
      - ./pillar:/srv/pillar
      - ./master/pki:/etc/salt/pki/master

  salt-minion:
    build:
      context: .
      dockerfile: docker/minion/Dockerfile
    container_name: salt-minion
    hostname: salt-minion
    depends_on:
      - salt-master
    networks:
      - salt-net
    volumes:
      - ./minion/config:/etc/salt/minion.d
      - ./minion/pki:/etc/salt/pki/minion
  
  lab-router-1:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    container_name: lab-router-1
    hostname: lab-router-1
    depends_on:
      - salt-master
    networks:
      - salt-net
    volumes:
      - ./lab-router-1/config:/etc/salt/proxy.d
      - ./lab-router-1/pki:/etc/salt/pki/proxy

  worker-1:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: worker-1
    hostname: worker-1
    depends_on:
      - salt-master
    networks:
      - salt-net
    volumes:
      - ./worker/config:/etc/salt/minion.d
      - ./worker/pki:/etc/salt/pki/minion

  web-1:
    build:
      context: .
      dockerfile: docker/minion/Dockerfile
    container_name: web-1
    hostname: web-1
    depends_on:
      - salt-master
    networks:
      - salt-net
    volumes:
      - ./web-1/config:/etc/salt/minion.d
      - ./web-1/pki:/etc/salt/pki/minion
  
  web-2:
    build:
      context: .
      dockerfile: docker/minion/Dockerfile
    container_name: web-2
    hostname: web-2
    depends_on:
      - salt-master
    networks:
      - salt-net
    volumes:
      - ./web-2/config:/etc/salt/minion.d
      - ./web-2/pki:/etc/salt/pki/minion

networks:
  salt-net:
    driver: bridge